const colors = {
  blue: {
    label: "Blue",
    nodeBg: "bg-blue-300",
    lightBg: "bg-blue-100",
    nodeBorder: "border-blue-600",
    accentBg: "bg-blue-500",
    textColor: "text-blue-600",
  },
  red: {
    label: "Red",
    nodeBg: "bg-red-300",
    lightBg: "bg-red-100",
    accentBg: "bg-red-500",
    nodeBorder: "border-red-600",
    textColor: "text-red-600",
  },
  yellow: {
    label: "Yellow",
    nodeBg: "bg-yellow-300",
    lightBg: "bg-yellow-100",
    accentBg: "bg-yellow-500",
    nodeBorder: "border-yellow-600",
    textColor: "text-yellow-600",
  },
  green: {
    label: "Green",
    nodeBg: "bg-green-300",
    lightBg: "bg-green-100",
    nodeBorder: "border-green-600",
    accentBg: "bg-green-500",
    textColor: "text-green-600",
  },
  pink: {
    label: "Pink",
    nodeBg: "bg-pink-300",
    lightBg: "bg-pink-100",
    nodeBorder: "border-pink-600",
    accentBg: "bg-pink-500",
    textColor: "text-pink-600",
  },
  orange: {
    label: "Orange",
    nodeBg: "bg-orange-300",
    lightBg: "bg-orange-100",
    nodeBorder: "border-orange-600",
    accentBg: "bg-orange-500",
    textColor: "text-orange-600",
  },
  purple: {
    label: "Purple",
    nodeBg: "bg-purple-300",
    lightBg: "bg-purple-100",
    nodeBorder: "border-purple-600",
    accentBg: "bg-purple-500",
    textColor: "text-purple-600",
  },
  default: {
    label: "Default",
    nodeBg: "bg-white",
    lightBg: "bg-slate-50",
    nodeBorder: "border-slate-300",
    accentBg: "bg-slate-500",
    textColor: "text-slate-600",
  },
  transparent: {
    label: "Transparent",
    nodeBg: "bg-transparent",
    lightBg: "bg-transparent",
    nodeBorder: "border-transparent",
    textColor: "text-slate-600",
    accentBg: "bg-transparent",
  },
} as const;

export { colors };
